resources:
  - name: qp-images
    type: git
    source:
      branch: master
      uri: git@github.com:Pivotal-DataFabric/qp-images.git
      private_key: {{qp_images_deploy_key}}
  - name: gpdb_perf
    type: docker-image
    __ignored: &dockerhub_credentials
      username: {{docker_username}}
      password: {{docker_password}}
    source:
      repository: pivotaldata/gpdb_perf
      <<: *dockerhub_credentials
  - name: gpdb_perf_dev_test
    type: docker-image
    source:
      repository: pivotaldata/gpdb_perf_dev_test
      <<: *dockerhub_credentials
jobs:
  - name: gpdb_perf
    plan:
    - get: qp-images
      trigger: true
    - put: gpdb_perf_dev_test
      params:
        build: qp-images/images/gpdb_perf
        cache: true
      get_params:
        save: true
    - task: test_gpdb_perf
      image: gpdb_perf_dev_test
      file: qp-images/images/gpdb_perf/test.yml
    - put: gpdb_perf
      params:
        load: gpdb_perf_dev_test
